version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nolatech-backend-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - DOMAIN_HOST=${DOMAIN_HOST}
      - DATABASE_SQLITE_NAME=${DATABASE_SQLITE_NAME}
      - DATABASE_CONNECTION_STRIN=${DATABASE_CONNECTION_STRIN}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_MAX_POOL=${DATABASE_MAX_POOL}
      - DATABASE_MIN_POOL=${DATABASE_MIN_POOL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-app.rule=Host(`${DOMAIN_HOST}`)
      - traefik.http.routers.backend-app.entrypoints=web
      - traefik.http.services.backend-app.loadbalancer.server.port=${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start
    networks:
      - app-network

networks:
  app-network:
