services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - DOMAIN_HOST=${DOMAIN_HOST}
      - DATABASE_SQLITE_NAME=${DATABASE_SQLITE_NAME}
      - DATABASE_CONNECTION_STRIN=postgres://postgres:password@database:5432/mydatabase
      - DATABASE_PORT=5432
      - DATABASE_HOST=database
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=postgres
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_PASSWORD=password
      - DATABASE_MAX_POOL=${DATABASE_MAX_POOL}
      - DATABASE_MIN_POOL=${DATABASE_MIN_POOL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-nolatech-backend.entrypoints=websecure"
      - "traefik.http.routers.api-nolatech-backend.tls.certResolver=letsencrypt"
      - "traefik.http.routers.api-nolatech-backend.rule=Host(`${DOMAIN_HOST}`)"
      - "traefik.http.services.api-nolatech-backend.loadbalancer.server.port=${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start
    networks:
      - dokploy-network

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  dokploy-network:
    external: true

volumes:
  db-data:
